### ISSUE TITLE
wifi不能用了，

### ISSUE THREAD

**Issue by xiaonibakeji** [daliansky/minisforum-u820-hackintosh#11]
wifi不能用了 下载的u820QQ群里的系统 ，带 的EFI显示不正常闪屏，升级到这个EFI显示正常点，但WIFI又不能用了
，唉

**Comment by zhukelili** [comment]
wifi出现感叹号，不能用 
![wifi出现感叹号，不能用](https://user-images.githubusercontent.com/17924080/141673934-2f714803-260e-4c59-be1a-881bc803a38f.png)
蓝牙一直打转，不能使用
![蓝牙打转](https://user-images.githubusercontent.com/17924080/141674027-c20f2fa8-d6a0-4e73-9780-376fe67cffd4.png)
蓝牙提示偏好设置错误
![蓝牙提示偏好设置错误](https://user-images.githubusercontent.com/17924080/141674034-51cca89b-fcc6-4412-a80f-dee76a9d9dbb.png)

**Comment by hululu1068** [comment]
> EFI_for_U820_OC_v2.0.0_HDMI_and_DP.zip
> 
> wifi出现感叹号，不能用 ![wifi出现感叹号，不能用](https://user-images.githubusercontent.com/17924080/141673934-2f714803-260e-4c59-be1a-881bc803a38f.png) 蓝牙一直打转，不能使用 ![蓝牙打转](https://user-images.githubusercontent.com/17924080/141674027-c20f2fa8-d6a0-4e73-9780-376fe67cffd4.png) 蓝牙提示偏好设置错误 ![蓝牙提示偏好设置错误](https://user-images.githubusercontent.com/17924080/141674034-51cca89b-fcc6-4412-a80f-dee76a9d9dbb.png)
根据安装的系统版本，替换EFI里面的AirportItlwm

**Comment by hululu1068** [comment]
1.8以后换成itlwm.kext了，在我这里Monterey和bigsur都不能用，后来换为AirportItlwm，并关闭SecureBootModel，WiFi、蓝牙、接力都正常了

**Comment by zhukelili** [comment]
> 1.8以后换成itlwm.kext了，在我这里Monterey和bigsur都不能用，后来换为AirportItlwm，并关闭SecureBootModel，WiFi、蓝牙、接力都正常了
我的系统是Monterey
[AirportItlwm_v2.0.0_stable_Monterey.kext.zip](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.0.0) 谢谢了，将里面的AirportItlwm.kext驱动拖到EFI/OC/Kexts/目录下，重启之后，WIFI工作正常了，但是蓝牙还是不能用！

**Comment by hululu1068** [comment]
> > 1.8以后换成itlwm.kext了，在我这里Monterey和bigsur都不能用，后来换为AirportItlwm，并关闭SecureBootModel，WiFi、蓝牙、接力都正常了
> > 我的系统是Monterey
> > [AirportItlwm_v2.0.0_stable_Monterey.kext.zip](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.0.0) 谢谢了，将里面的AirportItlwm.kext驱动拖到EFI/OC/Kexts/目录下，重启之后，WIFI工作正常了，但是蓝牙还是不能用！

删掉系统中关于蓝牙的.plist文件，重启电脑

**Comment by zhukelili** [comment]
> > > 1.8以后换成itlwm.kext了，在我这里Monterey和bigsur都不能用，后来换为AirportItlwm，并关闭SecureBootModel，WiFi、蓝牙、接力都正常了
> > > 我的系统是Monterey
> > > [AirportItlwm_v2.0.0_stable_Monterey.kext.zip](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.0.0) 谢谢了，将里面的AirportItlwm.kext驱动拖到EFI/OC/Kexts/目录下，重启之后，WIFI工作正常了，但是蓝牙还是不能用！
> 
> 删掉系统中关于蓝牙的.plist文件，重启电脑

你好，删除/Library/Preferences和~/Library/Preferences目录下名为com.apple.Bluetooth.plist的文件，重启之后还是不行，哭笑

**Comment by daliansky** [comment]
已经在配置文件 `config.plist` 中重新启用了`Airportitlwm for monterey`，弃用了 `itlwm` 驱动，这样对小白会友好些。
