### ISSUE TITLE
蓝牙键盘检测不到

### ISSUE THREAD

**Issue by allbutone** [daliansky/minisforum-u820-hackintosh#13]
安装的 Monterey 12.0.1, 使用的 EFI V2.0.0 Type-C + DP 版本， 但是蓝牙有点问题：
1. 蓝牙可以检测到小米蓝牙音响， 也可以连接正常使用
2. 蓝牙检测不到 京造 K3， 一直在转圈检测
3. 想关闭蓝牙让重新检测， 但关闭后却无法打开蓝牙了
4. 最后只好执行 sudo pkill bluetoothd 蓝牙才恢复， 但 K3 仍然检测不到，实测发现 win pc 和手机上都可以检测到 K3
目前我只能有线连接使用 K3，有相同情况的么？

**Comment by daliansky** [comment]
你只描述了蓝牙键盘是 `京造 K3` ，但是却没有描述使用的是什么无线网卡

<img width="780" alt="Xnip2021-12-02_09-11-16" src="https://user-images.githubusercontent.com/18546540/144339591-8d81a47e-81db-41fd-b2d3-14449846cbbd.png">

**Comment by allbutone** [comment]
无线网卡型号是 intel AC 7265, 使用  AirportItlwm-Monterey-v2.1.0 驱动, 替换了 U820 EFI V2.0 里的 itlwm
目前我已经连接上 K3 了, 但是过程是这样的:
![image](https://user-images.githubusercontent.com/4219875/144339950-e49aa520-5f15-4bad-8792-1e7af1c677ee.png)

**Comment by daliansky** [comment]
Intel无线网卡至少可以让你有限使用蓝牙，这已经是了不起的成就了；想使用完整的苹果生态建议还是要更换博通的无线网卡。
