### ISSUE TITLE
Need to flash the bios ?

### ISSUE THREAD

**Issue by TheNexter** [daliansky/minisforum-u820-hackintosh#14]
Do i need to flash the bios for hackintosh on this device ?
I have try to boot on my usb device but don't work, blackscreen :(

**Comment by daliansky** [comment]
不需要刷BIOS就可以安装使用黑苹果的，请进群查看安装教程，请下载最新的[EFI](https://github.com/daliansky/minisforum-u820-hackintosh/releases)
