### ISSUE TITLE
قمت بتحديث BIOS لكن بعد اعادة التشغيل احصل على شاشة سوداء وتعطيل كافة الملحقات 

### ISSUE THREAD

**Issue by Ahmedjaafar7004** [daliansky/minisforum-u820-hackintosh#15]
ماذا سيحدث يقولون لقد انتهى كل شي يمكنك فقط التمتع بصوت ويندوز
هل فعلا bios حرق حاسوبي

**Comment by daliansky** [comment]
Please report your question in English to get a reply, thank you
