### ISSUE TITLE
HDMI输出问题

### ISSUE THREAD

**Issue by aven-li** [daliansky/minisforum-u820-hackintosh#2]
大神好，我这边接入hdmi经常是黑屏或者花屏，DP输出偶尔也会闪屏（黑1~2s）

![image](https://user-images.githubusercontent.com/16175673/124372482-b004d080-dcbc-11eb-81b2-e91590a81e3f.png)

![image](https://user-images.githubusercontent.com/16175673/124372495-d62a7080-dcbc-11eb-9c48-f9d4ccf3e438.png)
看了下平台ID是模拟成了MacBook Pro 移动版的平台ID，接口那里也显示成了DP

这个有什么办法能完善？

**Comment by daliansky** [comment]
使用`Release`版本的EFI
