### ISSUE TITLE
Grey sreen

### ISSUE THREAD

**Issue by carilwang** [daliansky/minisforum-u820-hackintosh#3]
Use this command to create usb from my macbook air 
sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/MyVolume

Mount EFI, replaced the EFI contents, but grey screen every time. 

U820 16g/512, default bios and only disable boot security

**Comment by daliansky** [comment]
It may be necessary to set the DVMT to 64mb in the bios
