### ISSUE TITLE
macOS Big Sur 11.6.1 使用 u820 EFI v1.8.0, Intel I225-V 显示 ip 已分配, 但无法联网

### ISSUE THREAD

**Issue by allbutone** [daliansky/minisforum-u820-hackintosh#9]
使用 macOS Big Sur 11.6.1 20G221 Installer for OpenCore 0.7.5 and CLOVER 5141 and PE.dmg 和 u820 EFI v1.8.0 安装完毕后, 出现的问题:
1. 屏幕过几十秒闪烁一次
2. Intel I225-V 在 DHCP 下显示已分配 ip, 但实测发现无法访问网络, RTL8111 千兆网卡正常, 将 2.5G网口接在千兆交换机上, 显示连接IP已分配, 但无法联网, 将 2.5G 网口接在 2.5G 交换机上, 可以正常联网.

看 EFI 介绍里提到支持 Big Sur, 是不是仅支持到 Big Sur 的某个版本? 希望以后发布 EFI 版本时, 给出具体测试的系统版本, 这样安装时可以避免不少问题.

看了下 v1.8.0 的 config.plist, 发现针对 Intel I225-V 做了 kernel patch, MinKernel 为 19.0.0 MaxKernel 为 20.4.0, 对照 MacOS 版本的话, 20.4.0 应该是 Big Sur 11.3, 意思是当前 EFI 在 MacOS 11.3 以上的 Big Sur 不可用, 是这个意思吗?

**Comment by daliansky** [comment]
听说换dp线保平安
